// <auto-generated />
using System;
using CofferOS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CofferOS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CofferOSDbContext))]
    partial class CofferOSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("CofferOS.Domain.Wallets.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CurrentSats")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DerivationIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DescriptorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstTxId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsChange")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastTxId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScriptPubKeyHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UseCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DescriptorId");

                    b.HasIndex("Value");

                    b.HasIndex("WalletId");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("CofferOS.Domain.Wallets.Descriptor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Checksum")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DerivationPath")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSortedMulti")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MasterFingerprint")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScriptType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Threshold")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("descriptors", (string)null);
                });

            modelBuilder.Entity("CofferOS.Domain.Wallets.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("labels", (string)null);
                });

            modelBuilder.Entity("CofferOS.Domain.Wallets.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("CofferOS.Domain.Wallets.Utxo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<long?>("BlockHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Confirmations")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSpent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScriptPubKeyHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TxId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("ValueSats")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vout")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.HasIndex("WalletId", "TxId", "Vout")
                        .IsUnique();

                    b.ToTable("utxos", (string)null);
                });

            modelBuilder.Entity("CofferOS.Domain.Wallets.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("WatchOnly")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("wallets", (string)null);
                });

            modelBuilder.Entity("CofferOS.Domain.Wallets.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BlockHash")
                        .HasColumnType("TEXT");

                    b.Property<long?>("BlockHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Confirmations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("FeeSats")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NetAmountSats")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TxId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.HasIndex("WalletId", "TxId")
                        .IsUnique();

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("CofferOS.Domain.Wallets.Address", b =>
                {
                    b.HasOne("CofferOS.Domain.Wallets.Descriptor", null)
                        .WithMany("Addresses")
                        .HasForeignKey("DescriptorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CofferOS.Domain.Wallets.Descriptor", b =>
                {
                    b.HasOne("CofferOS.Domain.Wallets.Wallet", null)
                        .WithMany("Descriptors")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("CofferOS.Domain.Wallets.Cosigner", "Cosigners", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("DescriptorId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("KeyExpression")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("MasterFingerprint")
                                .HasMaxLength(16)
                                .HasColumnType("TEXT");

                            b1.Property<int>("OrderIndex")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("OriginPath")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("DescriptorId");

                            b1.ToTable("cosigners", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DescriptorId");
                        });

                    b.Navigation("Cosigners");
                });

            modelBuilder.Entity("CofferOS.Domain.Wallets.Utxo", b =>
                {
                    b.HasOne("CofferOS.Domain.Wallets.Wallet", null)
                        .WithMany("Utxos")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CofferOS.Domain.Wallets.WalletTransaction", b =>
                {
                    b.HasOne("CofferOS.Domain.Wallets.Wallet", null)
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CofferOS.Domain.Wallets.Descriptor", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("CofferOS.Domain.Wallets.Wallet", b =>
                {
                    b.Navigation("Descriptors");

                    b.Navigation("Transactions");

                    b.Navigation("Utxos");
                });
#pragma warning restore 612, 618
        }
    }
}
